spring:
  datasource:
    url: jdbc:postgresql://dpg-couj95n79t8c739il58g-a.frankfurt-postgres.render.com/real_estate_db_pea7
    username: admin
    password: kq70uP6WAyHA3tVUaoUMd811Fj0gbkvp
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
